/**
 * The teams and competitions to seed, exactly as requested.
 *
 * `aliases` exist only to raise the hit rate when matching against Highlightly's own
 * naming, which differs from common usage often enough to matter ("Bayern Munich",
 * "Korea Republic", "Carabao Cup"). `color` and `short` drive the monogram fallback that
 * the design uses whenever a crest is missing.
 *
 * Anything that does not resolve is simply left out of the catalog, and custom match entry
 * covers it.
 */

export const SEED_COMPETITIONS = [
  { name: 'Champions League', short: 'UCL', aliases: ['UEFA Champions League'] },
  { name: 'UEFA Super Cup', short: 'USC', aliases: ['UEFA Supercup'] },
  { name: 'LaLiga', short: 'LAL', aliases: ['La Liga', 'Primera Division', 'LaLiga EA Sports'], country: 'ES' },
  { name: 'Copa del Rey', short: 'CDR', aliases: ['Copa Del Rey'], country: 'ES' },
  { name: 'Supercopa de España', short: 'SCE', aliases: ['Super Cup', 'Supercopa de Espana'], country: 'ES' },
  { name: 'Premier League', short: 'EPL', aliases: ['English Premier League'], country: 'GB' },
  { name: 'Community Shield', short: 'CS', aliases: ['FA Community Shield'], country: 'GB' },
  { name: 'FA Cup', short: 'FAC', aliases: ['Emirates FA Cup'], country: 'GB' },
  { name: 'EFL Cup', short: 'EFL', aliases: ['Carabao Cup', 'League Cup'], country: 'GB' },
  { name: 'FIFA Club World Cup', short: 'CWC', aliases: ['Club World Cup'] },
  { name: 'FIFA Intercontinental Cup', short: 'ICC', aliases: ['Intercontinental Cup'] },
  { name: 'FIFA World Cup', short: 'WC', aliases: ['World Cup'] },
  { name: 'EURO', short: 'EURO', aliases: ['Euro Championship', 'European Championship', 'UEFA European Championship'] },
  { name: 'UEFA Nations League A', short: 'UNLA', aliases: ['Nations League A', 'UEFA Nations League'] },
  { name: 'Finalissima', short: 'FIN', aliases: ['CONMEBOL-UEFA Cup of Champions'] },
  { name: 'Copa América', short: 'CA', aliases: ['Copa America'] },
  { name: 'CONCACAF Gold Cup', short: 'GC', aliases: ['Gold Cup'] },
  { name: 'Bundesliga', short: 'BUN', aliases: ['1. Bundesliga'], country: 'DE' },
  { name: 'Serie A', short: 'SEA', aliases: [], country: 'IT' },
  { name: 'Ligue 1', short: 'LIG', aliases: ['Ligue 1 McDonalds'], country: 'FR' },
  { name: 'Copa Libertadores', short: 'LIB', aliases: ['CONMEBOL Libertadores'] },
  { name: 'Europa League', short: 'UEL', aliases: ['UEFA Europa League'] },
  { name: 'AFC Champions League Elite', short: 'ACLE', aliases: ['AFC Champions League'] },
  { name: 'Conference League', short: 'UECL', aliases: ['UEFA Europa Conference League', 'UEFA Conference League'] },
  { name: 'UEFA Nations League B', short: 'UNLB', aliases: ['Nations League B'] },
  { name: 'UEFA Nations League C', short: 'UNLC', aliases: ['Nations League C'] },
  { name: 'UEFA Nations League D', short: 'UNLD', aliases: ['Nations League D'] },
  { name: 'Africa Cup of Nations', short: 'AFCON', aliases: ['CAF Africa Cup of Nations'] },
  { name: 'African Nations Championship', short: 'CHAN', aliases: ['CAF African Nations Championship'] },
  { name: 'Asian Cup', short: 'AC', aliases: ['AFC Asian Cup'] },
  { name: 'SAFF Championship', short: 'SAFF', aliases: ['SAFF Cup'] },
  { name: 'DFB Pokal', short: 'DFB', aliases: ['DFB-Pokal'], country: 'DE' },
  // Two entries share the name "Super Cup"; the country hint is what tells them apart.
  { name: 'Super Cup', short: 'DFL', aliases: ['DFL Supercup', 'DFL-Supercup', 'Supercup'], country: 'DE' },
  { name: 'Coppa Italia', short: 'CI', aliases: [], country: 'IT' },
  { name: 'Supercoppa', short: 'SCI', aliases: ['Supercoppa Italiana', 'Super Cup'], country: 'IT' },
  { name: 'Coupe de France', short: 'CDF', aliases: [], country: 'FR' },
  { name: 'Trophée des champions', short: 'TDC', aliases: ['Trophee des Champions'], country: 'FR' },
  { name: 'Sidemen Charity Match', short: 'SDM', aliases: ['Sidemen Charity Football Match'] },
  { name: 'Soccer Aid', short: 'SA', aliases: ['Soccer Aid for UNICEF'] },
  { name: 'Indian Super League', short: 'ISL', aliases: ['Super League'], country: 'IN' },
  { name: 'Super Cup', short: 'ISC', aliases: ['Indian Super Cup'], country: 'IN' },
  { name: 'Durand Cup', short: 'DC', aliases: [], country: 'IN' },
];

export const SEED_TEAMS = [
  { name: 'Barcelona', short: 'BAR', color: '#A50044', aliases: ['FC Barcelona'] },
  { name: 'Arsenal', short: 'ARS', color: '#EF0107', aliases: ['Arsenal FC'] },
  { name: 'Real Madrid', short: 'RMA', color: '#FEBE10', aliases: ['Real Madrid CF'] },
  { name: 'Atlético Madrid', short: 'ATM', color: '#CB3524', aliases: ['Atletico Madrid', 'Atletico de Madrid'] },
  { name: 'Chelsea', short: 'CHE', color: '#0B4EA2', aliases: ['Chelsea FC'] },
  { name: 'Manchester United', short: 'MUN', color: '#DA291C', aliases: ['Man United', 'Manchester Utd'] },
  { name: 'Manchester City', short: 'MCI', color: '#6CABDD', aliases: ['Man City'] },
  { name: 'Liverpool', short: 'LIV', color: '#C8102E', aliases: ['Liverpool FC'] },
  { name: 'Tottenham Hotspur', short: 'TOT', color: '#132257', aliases: ['Tottenham'] },
  { name: 'Paris Saint-Germain', short: 'PSG', color: '#0B3D6E', aliases: ['Paris Saint Germain', 'PSG'] },
  { name: 'Bayern München', short: 'BAY', color: '#DC052D', aliases: ['Bayern Munich', 'FC Bayern München', 'Bayern Munchen'] },
  { name: 'Borussia Dortmund', short: 'BVB', color: '#FDE100', aliases: ['Dortmund'] },
  { name: 'Como', short: 'COM', color: '#0B3B8C', aliases: ['Como 1907'] },
  { name: 'Milan', short: 'MIL', color: '#FB090B', aliases: ['AC Milan'] },
  { name: 'Juventus', short: 'JUV', color: '#1A1A1A', aliases: ['Juventus FC'] },
  { name: 'Napoli', short: 'NAP', color: '#12A0D7', aliases: ['SSC Napoli'] },
  { name: 'Inter', short: 'INT', color: '#0068A8', aliases: ['Inter Milan', 'Internazionale', 'FC Internazionale'] },
  { name: 'Al Nassr', short: 'NAS', color: '#F9D616', aliases: ['Al-Nassr', 'Al Nassr FC'] },
  { name: 'Inter Miami', short: 'MIA', color: '#F7B5CD', aliases: ['Inter Miami CF'] },
  { name: 'Santos', short: 'SAN', color: '#E5E5E5', aliases: ['Santos FC'] },
  { name: 'Bengaluru FC', short: 'BFC', color: '#134FA2', aliases: ['Bengaluru'] },
  { name: 'Odisha FC', short: 'ODI', color: '#F05A28', aliases: ['Odisha'] },
  { name: 'Mohun Bagan SG', short: 'MBS', color: '#7A0026', aliases: ['Mohun Bagan Super Giant', 'Mohun Bagan', 'ATK Mohun Bagan'] },
  { name: 'Sidemen FC', short: 'SDM', color: '#E62B2B', aliases: ['Sidemen'] },
  { name: 'YouTube Allstars', short: 'YTA', color: '#FF0000', aliases: ['YouTube All Stars', 'YouTube Allstars FC'] },

  { name: 'India', short: 'IND', color: '#FF9933', national: true },
  { name: 'Spain', short: 'ESP', color: '#C60B1E', national: true },
  { name: 'England', short: 'ENG', color: '#CE1124', national: true },
  { name: 'France', short: 'FRA', color: '#1E3A8A', national: true },
  { name: 'Norway', short: 'NOR', color: '#BA0C2F', national: true },
  { name: 'Japan', short: 'JPN', color: '#12225B', national: true },
  { name: 'Morocco', short: 'MAR', color: '#C1272D', national: true },
  { name: 'South Korea', short: 'KOR', color: '#C60C30', national: true, aliases: ['Korea Republic', 'Republic of Korea'] },
  { name: 'Brazil', short: 'BRA', color: '#FEDF00', national: true },
  { name: 'Germany', short: 'GER', color: '#1A1A1A', national: true },
  { name: 'Italy', short: 'ITA', color: '#0066B2', national: true },
  { name: 'Netherlands', short: 'NED', color: '#F36C21', national: true, aliases: ['Holland'] },
  { name: 'Croatia', short: 'CRO', color: '#D32F2F', national: true },
  { name: 'USA', short: 'USA', color: '#0A3161', national: true, aliases: ['United States', 'United States of America'] },
  { name: 'Canada', short: 'CAN', color: '#D80621', national: true },
  { name: 'Türkiye', short: 'TUR', color: '#E30A17', national: true, aliases: ['Turkey', 'Turkiye'] },
  { name: 'Sweden', short: 'SWE', color: '#FECC00', national: true },
  { name: 'Belgium', short: 'BEL', color: '#E30613', national: true },
  { name: 'Australia', short: 'AUS', color: '#00843D', national: true },
  { name: 'Portugal', short: 'POR', color: '#046A38', national: true },
  { name: 'Argentina', short: 'ARG', color: '#75AADB', national: true },
];
